/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthRegisterRequest"];
                };
            };
            responses: {
                /** @description User created successfully */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetCookieHeader"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid input or account already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetCookieHeader"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Missing credentials */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reîmprospătează access token-ul folosind refresh token-ul din cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token nou generat */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetCookieHeader"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Refresh token lipsă sau invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returnează utilizatorul autentificat */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        /** @description Cookies cleared (accessToken, refreshToken) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description Internal server error (logout still clears cookies and returns 200 in implementation) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filtrează și sortează produsele
         * @description Endpoint principal pentru filtrarea produselor cu suport pentru toate tipurile de filtre
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Căutare full-text în nume și descriere
                     * @example cheese
                     */
                    q?: string;
                    /**
                     * @description Slug-ul categoriei
                     * @example pizza
                     */
                    categorySlug?: string;
                    /**
                     * @description Prețul minim (filtrare pe minPrice)
                     * @example 200
                     */
                    priceMin?: number;
                    /**
                     * @description Prețul maxim (filtrare pe minPrice)
                     * @example 500
                     */
                    priceMax?: number;
                    /**
                     * @description Flaguri separate prin virgulă sau flags[]=a&flags[]=b
                     * @example spicy,vegetarian
                     */
                    flags?: string;
                    /**
                     * @description Ingrediente separate prin virgulă sau ingredients[]=a&ingredients[]=b
                     * @example mozzarella,tomato
                     */
                    ingredients?: string;
                    /**
                     * @description Tipul de aluat
                     * @example thin
                     */
                    dough?: string;
                    /**
                     * @description Mărimea
                     * @example 30cm
                     */
                    size?: string;
                    /**
                     * @description Filtrează produsele care pot fi personalizate
                     * @example true
                     */
                    isCustomizable?: boolean;
                    /**
                     * @description Filtrează produsele noi (releasedAt în ultimele newerThanDays zile)
                     * @example true
                     */
                    isNew?: boolean;
                    /** @description Numărul de zile pentru care produsul este considerat nou */
                    newerThanDays?: number;
                    /** @description Criteriul de sortare (price sortează după minPrice) */
                    sort?: "price" | "rating" | "popularity" | "newest";
                    /** @description Ordinea de sortare */
                    order?: "asc" | "desc";
                    /** @description Numărul paginii */
                    page?: number;
                    /** @description Numărul de produse per pagină */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista filtrată de produse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrowseResponse"];
                    };
                };
                /** @description Parametri invalizi */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                            details?: {
                                field?: string;
                                message?: string;
                            }[];
                        };
                    };
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obține opțiunile de filtrare disponibile
         * @description Returnează toate opțiunile de filtrare cu numărul de produse pentru fiecare. Fără categorySlug → filtre globale; cu categorySlug → filtre contextuale (ținând cont de ceilalți parametri).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Căutare full-text în nume și descriere */
                    q?: string;
                    /**
                     * @description Slug-ul categoriei pentru filtrare specifică
                     * @example pizza
                     */
                    categorySlug?: string;
                    /** @description Prețul minim (filtrare pe minPrice) */
                    priceMin?: number;
                    /** @description Prețul maxim (filtrare pe minPrice) */
                    priceMax?: number;
                    /** @description Flaguri CSV sau flags[]=a&flags[]=b */
                    flags?: string;
                    /** @description Ingrediente CSV sau ingredients[]=a&ingredients[]=b */
                    ingredients?: string;
                    /** @description Tip aluat */
                    dough?: string;
                    /** @description Mărime */
                    size?: string;
                    isCustomizable?: boolean;
                    isNew?: boolean;
                    newerThanDays?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Opțiunile de filtrare */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                flags?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                ingredients?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                doughTypes?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                sizeOptions?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                price?: {
                                    min?: number;
                                    max?: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține coșul curent al utilizatorului */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Golește coșul utilizatorului */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adaugă o variantă de produs în coș (sau crește cantitatea dacă există) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Elimină un item din coș */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        /** Actualizează cantitatea unui item din coș */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obține toate categoriile
         * @description Returnează o listă cu toate categoriile din sistem, sortate alfabetic după nume.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu toate categoriile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Category"][];
                        };
                    };
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține o categorie după slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Slug-ul categoriei (valoarea toate nu este permisă) */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categoria găsită */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description Slug invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Categoria nu a fost găsită */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obține toate produsele (endpoint simplu)
         * @description Returnează toate produsele fără filtrare avansată. Pentru filtrare complexă, folosește /browse/products.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu toate produsele */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductListResponse"];
                    };
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/facets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obține valorile posibile (facets) pentru filtrele unei categorii (după slug)
         * @description Returnează colecțiile pentru filtre precum flags, ingredients, doughTypes, sizeOptions și intervalul de preț pentru categoria indicată prin slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Slug-ul categoriei (ex. carne, pizza) */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Facets obținute cu succes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Slug invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține un produs după ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description ID-ul produsului
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Produsul a fost găsit */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description ID invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Produsul nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listează ingredientele disponibile
         * @description Returnează lista cu toate ingredientele disponibile pentru pizza
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu ingredientele */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                id?: number;
                                key?: string;
                                label?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listează flagurile disponibile
         * @description Returnează lista cu toate flagurile disponibile pentru filtrare
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu flagurile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                id?: number;
                                key?: string;
                                label?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/dough-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listează tipurile de aluat disponibile
         * @description Returnează lista cu toate tipurile de aluat disponibile
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu tipurile de aluat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                id?: number;
                                key?: string;
                                label?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/size-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listează opțiunile de mărime disponibile
         * @description Returnează lista cu toate mărimile disponibile pentru pizza
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu mărimile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                id?: number;
                                key?: string;
                                label?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDTO: {
            /** @example 1 */
            id: number;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Ion Popescu */
            name?: string;
        };
        AuthResponse: {
            /** @example Autentificare reușită */
            message: string;
            user: components["schemas"]["UserDTO"];
        };
        LogoutResponse: {
            /** @example Logged out */
            message: string;
        };
        /**
         * @example {
         *       "email": "user@example.com",
         *       "password": "secret123",
         *       "name": "Ion"
         *     }
         */
        AuthRegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
        };
        /**
         * @example {
         *       "email": "user@example.com",
         *       "password": "secret123"
         *     }
         */
        AuthLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Error: {
            message: string;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
        ProductWithRelations: {
            id?: number;
            name?: string;
            description?: string;
            price?: number;
            minPrice?: number;
            maxPrice?: number;
            imageUrl?: string;
            popularity?: number;
            isCustomizable?: boolean;
            /** Format: date-time */
            releasedAt?: string;
            ratingAverage?: number;
            ratingCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            category?: {
                id?: number;
                name?: string;
                slug?: string;
            };
            flags?: {
                key?: string;
                label?: string;
            }[];
            ingredients?: {
                key?: string;
                label?: string;
            }[];
            variants?: {
                id?: number;
                price?: number;
                isDefault?: boolean;
                doughType?: {
                    key?: string;
                    label?: string;
                };
                sizeOption?: {
                    key?: string;
                    label?: string;
                };
            }[];
        };
        BrowseResponse: {
            message?: string;
            data?: components["schemas"]["ProductWithRelations"][];
            pagination?: {
                page?: number;
                limit?: number;
                total?: number;
            };
        };
        /** @description Tip de aluat pentru varianta de produs */
        DoughType: {
            /** @example 2 */
            id?: number;
            /** @example subtire */
            key?: string;
            /** @example Aluat Subțire */
            label?: string;
        };
        /** @description Opțiune de mărime pentru varianta de produs */
        SizeOption: {
            /** @example 3 */
            id?: number;
            /** @example mare */
            key?: string;
            /** @example Mare (35cm) */
            label?: string;
        };
        Category: {
            /**
             * @description ID-ul unic al categoriei
             * @example 1
             */
            id?: number;
            /**
             * @description Identificator URL-friendly al categoriei
             * @example carne
             */
            slug?: string;
            /**
             * @description Numele categoriei
             * @example Carne
             */
            name: string;
            /**
             * @description Descrierea categoriei
             * @example Produse din carne
             */
            description?: string;
            /**
             * Format: date-time
             * @description Data și ora creării
             * @example 2024-01-15T10:30:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Data și ora ultimei actualizări
             * @example 2024-01-15T10:30:00Z
             */
            updatedAt?: string;
        };
        CreateCategoryRequest: {
            /**
             * @description Numele categoriei
             * @example Carne
             */
            name: string;
            /**
             * @description Descrierea categoriei
             * @example Produse din carne de porc, vită, pui
             */
            description?: string;
        };
        UpdateCategoryRequest: {
            /**
             * @description Numele categoriei
             * @example Carne și mezeluri
             */
            name?: string;
            /**
             * @description Descrierea categoriei
             * @example Produse din carne și mezeluri
             */
            description?: string;
        };
        CategoryResponse: {
            /** @example Categoria a fost creată cu succes */
            message?: string;
            data?: components["schemas"]["Category"];
        };
        CategoryListResponse: {
            /** @example Categoriile au fost obținute cu succes */
            message?: string;
            data?: components["schemas"]["Category"][];
            /** @example 5 */
            count?: number;
        };
        CategoryStatsResponse: {
            /** @example Statisticile categoriilor au fost obținute cu succes */
            message?: string;
            data?: {
                /** @example 10 */
                totalCategories?: number;
            };
        };
        ErrorResponse: {
            /** @example Eroare de validare */
            error?: string;
        };
        Product: {
            /**
             * @description ID-ul unic al produsului
             * @example 1
             */
            id?: number;
            /**
             * @description Numele produsului
             * @example Carne de porc
             */
            name: string;
            /**
             * @description Descrierea produsului
             * @example Carne de porc proaspătă
             */
            description?: string;
            /**
             * Format: decimal
             * @description Prețul produsului
             * @example 25.5
             */
            price: number;
            /**
             * @description Cantitatea în stoc
             * @example 100
             */
            stock?: number;
            /**
             * @description ID-ul categoriei
             * @example 1
             */
            categoryId: number;
            /**
             * Format: date-time
             * @description Data și ora creării
             * @example 2024-01-15T10:30:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Data și ora ultimei actualizări
             * @example 2024-01-15T10:30:00Z
             */
            updatedAt?: string;
            category?: components["schemas"]["Category"];
        };
        CreateProductRequest: {
            /**
             * @description Numele produsului
             * @example Carne de porc
             */
            name: string;
            /**
             * @description Descrierea produsului
             * @example Carne de porc proaspătă
             */
            description?: string;
            /**
             * Format: decimal
             * @description Prețul produsului
             * @example 25.5
             */
            price: number;
            /**
             * @description Cantitatea în stoc
             * @example 100
             */
            stock?: number;
            /**
             * @description ID-ul categoriei
             * @example 1
             */
            categoryId: number;
        };
        UpdateProductRequest: {
            /**
             * @description Numele produsului
             * @example Carne de porc premium
             */
            name?: string;
            /**
             * @description Descrierea produsului
             * @example Carne de porc premium proaspătă
             */
            description?: string;
            /**
             * Format: decimal
             * @description Prețul produsului
             * @example 30
             */
            price?: number;
            /**
             * @description Cantitatea în stoc
             * @example 150
             */
            stock?: number;
            /**
             * @description ID-ul categoriei
             * @example 1
             */
            categoryId?: number;
        };
        UpdateStockRequest: {
            /**
             * @description Noua cantitate în stoc
             * @example 200
             */
            stock: number;
        };
        ProductResponse: {
            /** @example Produsul a fost creat cu succes */
            message?: string;
            data?: components["schemas"]["Product"];
        };
        ProductListResponse: {
            /** @example Produsele au fost obținute cu succes */
            message?: string;
            data?: components["schemas"]["Product"][];
            /** @example 10 */
            count?: number;
        };
        ProductStatsResponse: {
            /** @example Statisticile produselor au fost obținute cu succes */
            message?: string;
            data?: {
                /** @example 50 */
                totalProducts?: number;
            };
        };
        LowStockResponse: {
            /** @example Produsele cu stoc scăzut au fost obținute cu succes */
            message?: string;
            data?: components["schemas"]["Product"][];
            /** @example 5 */
            count?: number;
            /** @example 10 */
            threshold?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Header Set-Cookie care conține accesToken și refreshToken ca HTTP-only cookies */
        SetCookieHeader: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
